version: "3.3"
services:

  app:
    container_name: db-admin-app
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./api:/app
    depends_on:
      - pg_db
    env_file:
      - .env
  
  db:
    container_name: db-admin-db
    image: postgres:12
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env    

  pg_db:
    container_name: db-admin-pg-db
    image: postgres:12
    volumes:
      - pg_db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_db:
  db:
  api: