version: "3.3"
services:
  app:
    container_name: db-admin-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/app
    depends_on:
      - pg_db
    env_file:
      - .env

  db:
    container_name: db-admin-db
    image: postgres:12
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  pg_db:
    container_name: db-admin-pg-db
    image: postgres:12
    volumes:
      - pg_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=hardpassword
      - POSTGRES_DB=db_admin_db_slave
    ports:
      - "5432:5432"  

  pg_admin:
    container_name: db-admin-pg-admin
    image: dpage/pgadmin4
    ports:
      - "8080:8080"
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - .env

  mariadb:
    container_name: db-admin-mariadb
    image: docker.io/bitnami/mariadb:10.3
    environment: 
      - MARIADB_DATABASE=db_admin_db_slave
      - MARIADB_ROOT_PASSWORD=somebeach123
    volumes:
      - mariadb_data:/bitnami/mariadb

  phpmyadmin:
    container_name: db-admin-phpmyadmin
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - "8081:8080"
      - "443:8443"

    env_file:
      - .env

volumes:
  pg_db:
  db:
  api:
  pgadmin:
  mariadb_data:
    driver: local
